spring:
  config:
    import: optional:configserver:http://13.124.204.48:8081
  application:
    name: user-service, common-config
  profiles:
    active: default

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER01},${KAFKA_CLUSTER02},${KAFKA_CLUSTER03}


management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

