spring:
  config:
    import: optional:configserver:http://13.124.204.48:8081
  application:
    name: user-service
  profiles:
    active: default

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
