spring:
  config:
    import: optional:configserver:http://localhost:8081
  application:
    name: user-service
  profiles:
    active: default

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

  kafka:
    bootstrap-servers: 192.168.56.101:9092


management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

