server:
  port: 0 # 랜덤하게 지정

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defalutZone: http://localhost:8761/eureka  
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
spring:
  application:
    name: chat-service  
    
  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER01:43.201.135.148:9092},${KAFKA_CLUSTER02:43.200.40.62:9092},${KAFKA_CLUSTER03:43.201.243.40:9092}


